fullname: Dmitrii Kovrizhnukh
favicon: /assets/images/favicon.svg



show_info: true

location: Russia
language: Russian, English, ein bi√üchen Deutsch
phone number: 89119675178

show_contacts: true
mailto: mailto:kovrizhnykh.diu@phystech.edu
cv_pdf_link: https://github.com/HCL-271/HCL-271.github.io/blob/main/pdf/hcl-271_github_io_english_.pdf
phone number: 89119675178

remote_theme: annndruha/minimal-resume
plugins:
- jekyll-remote-theme
